version: '2'
services:
  backend:
    build: ./backend
#    ports:
#     - "8000:8000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
    tty: true
    volumes:
     - ./backend/api:/app/api
  db:
    build: ./db
#    ports:
#      - "3306:3306"
  ui:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - API_HOST=backend
    tty: true
    volumes:
      - ./frontend/paypay:/app
      - ./frontend/pizzashop/build1:/usr/share/nginx/html
    ports:
      - "80:80"





