const constants = {
	ADD_DAY:"ADD_DAY",

	ADD_TO_CART:"ADD_TO_CART",
	REMOVE_FROM_CART:"REMOVE_FROM_CART",
	DECREASE_QUANTITY_OF_PRODUCT_FROM_CART:"DECREASE_QUANTITY_OF_PRODUCT_FROM_CART",
	INCREASE_QUANTITY_OF_PRODUCT_FROM_CART:"INCREASE_QUANTITY_OF_PRODUCT_FROM_CART",
	PROCEED_TO_CHECKOUT:"PROCEED_TO_CHECKOUT",
	POST_ORDER:"POST_ORDER",

	REMOVE_DAY:"REMOVE_DAY",
	SET_GOAL:"SET_GOAL",

	ADD_ERROR:"ADD_ERROR",
	CLEAR_ERROR:"CLEAR_ERROR",
	FETCH_PRODUCTS:"FETCH_PRODUCTS",
	CANCEL_FETCHING:"CANCEL_FETCHING",
	CHANGE_PRODUCTS:"CHANGE_PRODUCTS",
	CLEAR_PRODUCTS:"CLEAR_PRODUCTS",
	CHANGE_CURRENCY:"CHANGE_CURRENCY",





	CHANGE_SUGGESTIONS:"CHANGE_SUGGESTIONS",
	CLEAR_SUGGESTIONS:"CLEAR_SUGGESTIONS",



};

export const url = 'http://localhost:8000/api';
export default constants
