const constants = {


	ADD_TO_CART:"ADD_TO_CART",
	REMOVE_FROM_CART:"REMOVE_FROM_CART",
	EMPTY_CART_AFTER_ORDER_SUCCESS:"EMPTY_CART_AFTER_ORDER_SUCCESS",
	DECREASE_QUANTITY_OF_PRODUCT_FROM_CART:"DECREASE_QUANTITY_OF_PRODUCT_FROM_CART",
	INCREASE_QUANTITY_OF_PRODUCT_FROM_CART:"INCREASE_QUANTITY_OF_PRODUCT_FROM_CART",

	PROCEED_TO_CHECKOUT:"PROCEED_TO_CHECKOUT",
	POST_ORDER:"POST_ORDER",
	ORDER_PLACED:"ORDER_PLACED",
	POST_ORDER_FAIL:"POST_ORDER_FAIL",




	ADD_ERROR:"ADD_ERROR",
	CLEAR_ERROR:"CLEAR_ERROR",

	FETCH_PRODUCTS:"FETCH_PRODUCTS",
	CANCEL_FETCHING:"CANCEL_FETCHING",
	CHANGE_PRODUCTS:"CHANGE_PRODUCTS",
	CLEAR_PRODUCTS:"CLEAR_PRODUCTS",

	FETCH_ORDER_HISTORY:"FETCH_ORDER_HISTORY",
	CANCEL_FETCHING_ORDER_HISTORY:"CANCEL_FETCHING_ORDER_HISTORY",
	CHANGE_ORDER_HISTORY:"CHANGE_ORDER_HISTORY",
	ADD_ORDER_HISTORY:"ADD_ORDER_HISTORY",
	CLEAR_ORDER_HISTORY:"CLEAR_ORDER_HISTORY",

	CHANGE_CURRENCY:"CHANGE_CURRENCY",

	REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
	REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
	REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
	LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',




	LOGOUT: 'USERS_LOGOUT',









};

export const url = `http://${window.location.hostname}/api`;
export default constants
